### ISSUE TITLE
申请翻译With open data, you finally get what you’ve paid for all these years

### ISSUE THREAD

**Issue by yeszhangyi** [FreeCodeCampChina/blog#1]
公司：昆山市陆家镇环境保护办公室 
学校：华侨大学
工作内容/专业：如公司，环境工程
常浏览的国外网站：无
英语水平：蛮烂的，两天内翻译完可以吗？一般多少时间
个人博客：无
申请翻译With open data, you finally get what you’ve paid for all these years

**Comment by huluoyang** [comment]
每个人都是从翻译小白过来的，我也不例外。
去年我才开始翻译英文文章，进度也很慢。
时间在一周之内。

**Comment by jhonny-me** [comment]
@JackJin2014 替换图片链接。

**Comment by jhonny-me** [comment]
closing.
