### ISSUE TITLE
申请翻译I finally made sense of front end build tools. You can, too.

### ISSUE THREAD

**Issue by yajiefeng** [FreeCodeCampChina/blog#13]
[I finally made sense of front end build tools. You can, too.](https://medium.freecodecamp.com/making-sense-of-front-end-build-tools-3a1b3a87043b#.jntd5ha7b)
公司：深圳掌玩网络
工作内容/专业：后台开发
常浏览的国外网站：twitter，medium
英语水平：很一般
个人博客：jieniu.me（没怎么维护）

**Comment by JackJin2014** [comment]
👍 我来添加进来

**Comment by yajiefeng** [comment]
翻译完成

**Comment by jhonny-me** [comment]
校对完成。请替换图片链接。
@JackJin2014
