### ISSUE TITLE
申请翻译 Transparency in Action: Free Code Camp is Now Open Source

### ISSUE THREAD

**Issue by soyaine** [FreeCodeCampChina/blog#14]
博客：[soyaine](https://soyaine.github.io)
想翻译的文章：Transparency in Action: Free Code Camp is Now Open Source
之前参与翻译过：[GitHub 正……](https://www.oschina.net/translate/github-the-full-inside-story-2016-2) 第三段... =.= [MDN的一些文档](https://developer.mozilla.org/zh-CN/profiles/soyaine)
最近时间比较紧张，但是想贡献点力量。一周左右完成可以吗？

**Comment by JackJin2014** [comment]
👍  你在翻译微信群吗？加我微信jinjian0414留言 翻译 :-)

**Comment by soyaine** [comment]
翻译完成 
原文链接：[Transparency in Action: Free Code Camp is Now Open Source](https://medium.freecodecamp.com/transparency-in-action-free-code-camp-is-now-open-source-9dae1985d925#.1zh20tm2o)

译文链接：[开源行动：Free Code Camp 正式开源](https://github.com/FreeCodeCampChina/blog/blob/master/Translation/2016-10-28-%E5%BC%80%E6%BA%90%E8%A1%8C%E5%8A%A8-FreeCodeCamp%E6%AD%A3%E5%BC%8F%E5%BC%80%E6%BA%90.md)
