### ISSUE TITLE
申请翻译JavaScript Fatigue Fatigue

### ISSUE THREAD

**Issue by cxhy** [FreeCodeCampChina/blog#15]
公司： sec-chip
工作内容：SOC集成
常浏览的国外网站：opencores
英语水平：CET-4
个人博客：[DMA_Master](http://www.jianshu.com/users/49eea32c720d/latest_articles)`
申请翻译：[JavaScript Fatigue Fatigue](https://medium.freecodecamp.com/javascript-fatigue-fatigue-66ffb619f6ce#.67f2lhseu)

**Comment by cxhy** [comment]
翻译已完成，已发PR。请校对。
@JackJin2014

**Comment by jhonny-me** [comment]
校对完成。
assigned to @JackJin2014

**Comment by jhonny-me** [comment]
closing
