### ISSUE TITLE
申请翻译From Zero to Front-end Hero

### ISSUE THREAD

**Issue by yajiefeng** [FreeCodeCampChina/blog#18]
[From Zero to Front-end Hero](https://medium.freecodecamp.com/from-zero-to-front-end-hero-part-1-7d4f7f0bff02?gi=f8d3bb6a59ba)

**Comment by jhonny-me** [comment]
@jieniu 请问翻译完了吗？如果翻译完成请发个pr。O(∩_∩)O谢谢

**Comment by yajiefeng** [comment]
@jhonny-me 快了，前段时间搬家，耽搁了

**Comment by yajiefeng** [comment]
完成了，pr

**Comment by jhonny-me** [comment]
closing
