### ISSUE TITLE
申请翻译My journey to becoming a web developer from scratch without a CS degree, 2 years later (and what I learned from it)

### ISSUE THREAD

**Issue by EchoLoveCoding** [FreeCodeCampChina/blog#19]
翻译文章当中“HTML & CSS”-“AngularJS”部分。（第一次翻，少来点。。。

This is Echo from Shanghai, graduated from CUFE, major in Marketing.
English：CET-6...

**Comment by jhonny-me** [comment]
@JackJin2014 请将该篇长文拆分为多个部分在readme进行更新，现在这样不好追踪。

**Comment by jhonny-me** [comment]
finished.closing...
