### ISSUE TITLE
申请翻译 Free Code Camp Christmas Special: Giving the Gift of Open Data

### ISSUE THREAD

**Issue by hilaily** [FreeCodeCampChina/blog#2]
公司：开源中国
工作内容：java 开发
常浏览的国外网站：reddit
英语水平：很水，这个周末（10月2日）之前搞定吧
个人博客：blog.laily.net （好久没更了）
申请翻译 Free Code Camp Christmas Special: Giving the Gift of Open Data

**Comment by huluoyang** [comment]
thanks for your contribution.
我的英文也菜，翻译也要靠字典。
用进废退，编程和英文一样，需要长期练习。
欢迎你参与翻译，已通过。

**Comment by jhonny-me** [comment]
@JackJin2014 已校对，请替换cdn链接，或者教我下怎么替换。。。

**Comment by jhonny-me** [comment]
closing
