### ISSUE TITLE
申请翻译What programming language should you learn first? ʇdıɹɔsɐʌɐɾ :ɹǝʍsuɐ

### ISSUE THREAD

**Issue by merlinyx** [FreeCodeCampChina/blog#23]
各位好！想申请翻译一篇文章。应该周五可以完成！

公司/学校：columbia engineering
工作内容/专业: computer science
常浏览的国外网站: new york times, documentations, github, etc.
英语水平: t115, have experience and interest in translation

这篇[文章](https://medium.freecodecamp.com/what-programming-language-should-i-learn-first-%CA%87d%C4%B1%C9%B9%C9%94s%C9%90%CA%8C%C9%90%C9%BE-%C9%B9%C7%9D%CA%8Dsu%C9%90-19a33b0a467d#.7o2bqyds7)是四天前Quincy Larson发的，博客上最新一篇应该。

**Comment by merlinyx** [comment]
已经翻好了！请问如何提交？

**Comment by jhonny-me** [comment]
@merlinyx 给我们发一个pr。
 https://help.github.com/articles/creating-a-pull-request/

**Comment by merlinyx** [comment]
抱歉！最近有点忙没看github，pr发了。谢谢！

**Comment by jhonny-me** [comment]
closing
