### ISSUE TITLE
申请翻译zero-to-front-end-hero(2 part)

### ISSUE THREAD

**Issue by yajiefeng** [FreeCodeCampChina/blog#25]
[zero-to-front-end-hero(2 part)](https://medium.com/p/adfa4824da9b)

接着翻译第二部分

**Comment by yajiefeng** [comment]
完成翻译20161118_前端开发从草根到英雄2.md

**Comment by yajiefeng** [comment]
原文链接可以附上
http://www.jianshu.com/p/e2be2bb9d229

**Comment by jhonny-me** [comment]
closing
