### ISSUE TITLE
申请翻译 So Yeah We Tried Slack… and We Deeply Regretted It

### ISSUE THREAD

**Issue by jhonny-me** [FreeCodeCampChina/blog#3]
- 公司：Wiredcraft
- 工作内容：iOS 开发
- 常浏览的国外网站：The hacker news, Github!!!
- 英语水平：一般
- 个人博客：http://www.colockeder.com  (基本不用)
- 申请翻译:  So Yeah We Tried Slack… and We Deeply Regretted It

**Comment by huluoyang** [comment]
Wiredcraft 有点像巫妖王啊，是游戏公司吧。
Welcome back.

**Comment by jhonny-me** [comment]
哈哈哈哈。。。。。不是。
昨天看群里好像有人认领了这篇了？

**Comment by huluoyang** [comment]
是的，有人认领了这篇。
你只能换另一篇了。

**Comment by jhonny-me** [comment]
开了个新issue，这个我关掉了。
