### ISSUE TITLE
申请翻译 Let’s explore ES6 Generators

### ISSUE THREAD

**Issue by soyaine** [FreeCodeCampChina/blog#32]
申请翻译文章：[Let’s explore ES6 Generators](https://medium.freecodecamp.org/lets-explore-es6-generators-5e58ed23b0f1)

**Comment by soyaine** [comment]
翻译完成，请校对。
pr: https://github.com/FreeCodeCampChina/blog/pull/33

**Comment by winar-jin** [comment]
已合并。

**Comment by winar-jin** [comment]
已合并。
