### ISSUE TITLE
申请翻译 How I built a mailing list signup form right into Medium using Google Forms

### ISSUE THREAD

**Issue by jhonny-me** [FreeCodeCampChina/blog#4]
- 公司：Wiredcraft
- 工作内容：iOS 开发
- 常浏览的国外网站：The hacker news, Github!!!
- 英语水平：一般
- 个人博客：http://www.colockeder.com  (基本不用)
- 申请翻译:  How I built a mailing list signup form right into Medium using Google Forms

**Comment by huluoyang** [comment]
OK，这就是纯粹练英文的节奏啊。
好东西都在国外，翻译者无私奉献啊。

**Comment by jhonny-me** [comment]
@huluoyang 
文中有一些Medium的feature，用MD估计不太好弄，我就直接用截图了啊。

**Comment by huluoyang** [comment]
有图有真相

**Comment by jhonny-me** [comment]
已pr，请review。
@huluoyang
