### ISSUE TITLE
申请翻译 Things you probably didn’t know you could do with Chrome’s Develo

### ISSUE THREAD

**Issue by yajiefeng** [FreeCodeCampChina/blog#5]
公司：深圳掌玩网络
工作内容/专业：后台开发
常浏览的国外网站：twitter，medium
英语水平：很一般
个人博客：jieniu.me（没怎么维护）
申请翻译[Things you probably didn’t know you could do with Chrome’s Develo](https://medium.freecodecamp.com/10-tips-to-maximize-your-javascript-debugging-experience-b69a75859329#.ttyklsrhi)

**Comment by JackJin2014** [comment]
👍   加我微信jinjian0414 邀请加入 翻译微信群

**Comment by jhonny-me** [comment]
校对完成。
assign to @JackJin2014
