### ISSUE TITLE
对于github label的使用建议

### ISSUE THREAD

**Issue by jhonny-me** [FreeCodeCampChina/blog#7]
介于目前使用的issue申领的方式，建议使用github为issue提供的label功能，可以设置诸如：
- 申领中
- 翻译中
- 翻译完成
- 已拒绝
- 重新校验
- 定稿

的label，来为每篇文章的进度可视化，并为每个流程assign对应的负责人。实现流程进度可追踪。完结状态的issue确认无误后可以及时关闭。（因为目前在职的公司就是使用的git工作流，感觉十分受用）普通的用户貌似无法对自己创建的issus添加label，所以还是需要管理人员来做这些事，另外，既然已经放到组织下来了，怎么不添加一些成员呐。

@huluoyang @JackJin2014

**Comment by huluoyang** [comment]
确实如此啊，git flow 我也是新手。
欢迎你们参与进来，我邀请你进来。

**Comment by jhonny-me** [comment]
label已添加。

@huluoyang @JackJin2014
